[project]
name = "dogvision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "onvif-zeep>=0.2.12",
    "opencv-python>=4.11.0.86",
    "zeep>=4.3.1",
]
